# ______  ___ _   _
# | ___ \|_  | | | |
# | |_/ /  | | |_| |
# |  __/   | |  _  |
# | |  /\__/ / | | |
# \_|  \____/\_| |_/
# Starship prompt config file
# should be in ~/.config/starship.toml
# Contains modified examples from https://starship.rs/config/

# Don't print a new line at the start of the prompt
add_newline = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ”Œ"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 100
style = "green"

[conda]
disabled = true
format = "[$symbol$environment](dimmed green) "

[directory]
truncate_to_repo = true
truncation_length = 1
truncation_symbol = "â€¦/"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

# Because why not
[elixir]
symbol = "ğŸ”® "

# Environment variables, configure here for cross-shell compatibility
[env_var]
disabled = true
# variable = "SHELL"
# default = "/usr/bin/fish"
[gcloud]
disabled = true

[git_branch]
symbol = "ğŸŒ±"
truncation_length = 50
truncation_symbol = "â€¦"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨ â‡¡${count}"
behind = "ğŸ˜° â‡£${count}"
diverged = "ğŸ˜µ â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
format = "via [ğŸğŸ’¨ $version](bold cyan) "

[helm]
format = "via [â˜¸ $version](bold white) "

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
# trim_at = ".companyname.com" # Change accordingly
disabled = false

[java]
symbol = "â˜• "

[jobs]
symbol = "+ "
threshold = 1

[julia]
symbol = "âˆ´ "

[kotlin]
symbol = "ğŸ…º "
kotlin_binary = "kotlinc"

[kubernetes]
format = 'on [â˜¸ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[line_break]
disabled = false

# [lua]
# format = "via [ğŸŒ™ $version](bold blue) "

[memory_usage]
disabled = false
format = " $symbol [${ram}( | ${swap})]($style)"
threshold = -1
symbol = ""
style = "bold dimmed green"

[nodejs]
format = "via [â¬¢ $version](bold green)"

# Not that I would use it, but a Camel on a prompt can't hurt.
[ocaml]
format = "via [ğŸª $version]($style) "

[openstack]
format = "on [$symbol$cloud(\\($project\\))]($style) "
style = "bold yellow"
symbol = "â˜ï¸ "

[package]
format = "via [ğŸ“¦    $version](208 bold) "

[perl]
format = "via [ğŸ˜ $version]($style) "

[php]
format = "via [ğŸ”¹ $version](147 bold) "

[purescript]
format = "via [$symbol$version](bold white)"

[python]
symbol = "ğŸ "
pyenv_version_name = true
python_binary = "python3"

[ruby]
symbol = "ğŸ’ "

[rust]
format = "via [$symbol $version](red bold)"

[status]
map_symbol = true
disabled = false

[swift]
format = "via [$symbol  $version](red bold)"

[time]
disabled = false
format = 'ğŸ•™[ $time]($style) '

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[vagrant]
format = "via [â± $version](bold white) "

[zig]
symbol = "âš¡ï¸ "